import { VehicleCategory, VehicleConfig } from '../types';

// Internal vehicle speed is measured in world units per simulation tick.
// Configured top speeds and acceleration values use km/h-based units.
export const KMH_TO_WORLD_SPEED = 1 / 3.6;

export const VEHICLE_CONFIGS: Record<VehicleCategory, VehicleConfig> = {
  kamaz_dump: {
    id: 'kamaz_dump',
    name: 'KAMAZ 65115 Dump Truck',
    nameRu: 'КАМАЗ 65115 Самосвал',
    width: 32,
    length: 74,
    mass: 4200,
    maxSpeed: 95,
    acceleration: 30,
    braking: 55,
    turnSpeed: 3.2,
    reverseSpeed: 28,
    driftFriction: 0.94,
    durability: 450,
    defaultColor: '#f97316', // Orange
    cargoCapacity: 5,
    description: 'Легендарный трёхосный самосвал. Мощный дизельный двигатель, огромная грузоподъёмность и несгибаемый характер.',
  },
  kamaz_flatbed: {
    id: 'kamaz_flatbed',
    name: 'KAMAZ 5320 Flatbed',
    nameRu: 'КАМАЗ 5320 Бортовой',
    width: 32,
    length: 80,
    mass: 4000,
    maxSpeed: 100,
    acceleration: 32,
    braking: 58,
    turnSpeed: 3.3,
    reverseSpeed: 28,
    driftFriction: 0.93,
    durability: 420,
    defaultColor: '#0284c7', // Blue
    cargoCapacity: 8,
    description: 'Классический бортовой грузовик для дальних перевозок контейнеров, техники и стройматериалов.',
  },
  heavy_4x4: {
    id: 'heavy_4x4',
    name: 'Heavy Duty 4x4',
    nameRu: 'Внедорожник 4х4 Heavy Duty',
    width: 26,
    length: 52,
    mass: 2200,
    maxSpeed: 130,
    acceleration: 48,
    braking: 65,
    turnSpeed: 3.8,
    reverseSpeed: 38,
    driftFriction: 0.91,
    durability: 300,
    defaultColor: '#334155', // Slate
    cargoCapacity: 2,
    description: 'Тяжёлый рамный пикап 4х4 с усиленным бампером и отличной проходимостью.',
  },
  ambulance: {
    id: 'ambulance',
    name: 'City Ambulance',
    nameRu: 'Скорая Помощь',
    width: 25,
    length: 54,
    mass: 1900,
    maxSpeed: 140,
    acceleration: 54,
    braking: 70,
    turnSpeed: 4.0,
    reverseSpeed: 42,
    driftFriction: 0.89,
    durability: 240,
    defaultColor: '#ffffff', // White with Red Cross
    hasSiren: true,
    description: 'Реанимобиль с громкой спецсиреной и проблесковыми маячками. Пропускается всеми на перекрёстках.',
  },
  police: {
    id: 'police',
    name: 'Police Interceptor',
    nameRu: 'ДПС Патрульная',
    width: 23,
    length: 48,
    mass: 1600,
    maxSpeed: 165,
    acceleration: 70,
    braking: 80,
    turnSpeed: 4.4,
    reverseSpeed: 48,
    driftFriction: 0.88,
    durability: 260,
    defaultColor: '#0f172a', // Dark Navy/White
    hasSiren: true,
    description: 'Патрульный перехватчик с форсированным мотором, красно-синей люстрой и повышенной управляемостью.',
  },
  sedan: {
    id: 'sedan',
    name: 'Classic Sedan',
    nameRu: 'Городской Седан',
    width: 22,
    length: 46,
    mass: 1350,
    maxSpeed: 140,
    acceleration: 55,
    braking: 70,
    turnSpeed: 4.2,
    reverseSpeed: 38,
    driftFriction: 0.87,
    durability: 180,
    defaultColor: '#0d9488', // Teal/Cyan as in screenshot
    description: 'Удобный и сбалансированный четырёхдверный седан для повседневных поездок по городу.',
  },
  hatchback: {
    id: 'hatchback',
    name: 'Compact Hatchback',
    nameRu: 'Компактный Хэтчбек',
    width: 20,
    length: 38,
    mass: 1100,
    maxSpeed: 130,
    acceleration: 58,
    braking: 75,
    turnSpeed: 4.6,
    reverseSpeed: 38,
    driftFriction: 0.86,
    durability: 150,
    defaultColor: '#e11d48', // Red
    description: 'Маневренный городской хэтчбек. Легко паркуется и быстро разгоняется.',
  },
  sports: {
    id: 'sports',
    name: 'GT Sports Coupe',
    nameRu: 'Спорткупе GT',
    width: 23,
    length: 46,
    mass: 1250,
    maxSpeed: 190,
    acceleration: 90,
    braking: 90,
    turnSpeed: 4.8,
    reverseSpeed: 52,
    driftFriction: 0.82, // Slides easily for drifting
    durability: 160,
    defaultColor: '#9333ea', // Purple
    description: 'Быстрое заднеприводное купе с низким центром тяжести для дрифта и гонок по проспектам.',
  },
  bus: {
    id: 'bus',
    name: 'City Transit Bus',
    nameRu: 'Городской Автобус ЛиАЗ',
    width: 32,
    length: 96,
    mass: 5200,
    maxSpeed: 80,
    acceleration: 24,
    braking: 45,
    turnSpeed: 2.6,
    reverseSpeed: 22,
    driftFriction: 0.95,
    durability: 550,
    defaultColor: '#2563eb', // Blue
    cargoCapacity: 25,
    description: 'Вместительный пассажирский автобус. Медленно разгоняется, но сносит любые легковушки на пути.',
  },
  taxi: {
    id: 'taxi',
    name: 'City Yellow Taxi',
    nameRu: 'Городское Такси',
    width: 22,
    length: 46,
    mass: 1350,
    maxSpeed: 140,
    acceleration: 56,
    braking: 72,
    turnSpeed: 4.3,
    reverseSpeed: 38,
    driftFriction: 0.88,
    durability: 190,
    defaultColor: '#eab308', // Yellow
    description: 'Жёлтое такси с шашечками на крыше для выполнения заказов по перевозке пассажиров.',
  },
};
